\documentclass{article}
\usepackage[utf8]{inputenc}

\begin{document}

\section{Introduction}
\label{sec:title}
Test

\subsection{Subtitle}
\label{ssec:subtitle}

Plain text.
<<>>=
getwd()
orig_df = read.csv("Assets/globalterrorismdb.csv")  # read csv file
my_df <- orig_df
attach(my_df)
dim(my_df)
@


\subsection{Another subtitle}
\label{ssec:another_subtitle}

More plain text.

\end{document}